services:
  backend:
    image: ghcr.io/dwikis17/heydwiki-backend:latest
    env_file:
      - .env.backend
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    image: ghcr.io/dwikis17/portf:latest
    env_file:
      - .env.frontend
    environment:
      PORT: "3000"
    ports:
      - "4173:3000"
    restart: unless-stopped